consumer:
  auto:
    test:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
  file:
    name: /tsf-demo-logs/${spring.application.name}/root.log